### ISSUE TITLE
Add simple datarule and dispatch support to spec command

### ISSUE THREAD

**Issue by dweaver** [exosite/exoline#109]

**Comment by maanenson** [comment]
Would find it very useful to have this - so that datarules and dispatches can be specified in the spec file.  A lot can be done with datarules and dispatches that are subscribed to dataports, in addition many of the functions of these two resources are not made available in Portals manage pages, thus a greater need for supporting in Exoline spec files.

**Comment by dweaver** [comment]
This one is close. What's left is to support --generate for datarules and dispatches

**Comment by dweaver** [comment]
datarule and dispatch support is in Exoline 0.9.16, released just now.

**Comment by dweaver** [comment]
Here are some example specs:

https://github.com/exosite/exoline/blob/master/test/files/spec_datarule.yaml
https://github.com/exosite/exoline/blob/master/test/files/spec_dispatch.yaml

There are also examples here:

```
$ exo spec --example
```
